### ISSUE TITLE
[Bug] National Insurance calculations not working correctly for 2-weekly payrolls

### ISSUE THREAD

**Issue by paytools-master** [paytools-fdn/Paytools.Core#1]
**Describe the bug**

When PayFrequency is set to PayFrequency.TwoWeekly, National Insurance calculation results don't match HMRC published test data.

**Module(s) affected (if applicable)** : Paytools.NationalInsurance

**Steps to reproduce**

Run National Insurance unit test with TestIdentifier: **1671631561/Cat-A/20** which generates the following output:

```
Expected test.EmployeeNiContribution to be 174.01M because input is { TestIdentifier: '1671631561/Cat-A/20',
PayFrequency: TwoWeekly, Period: 16, GrossPay: 1933.72, EmployeeNiContribution: 173.97, EmployerNiContribution: 218.55,  }
 and output is Up And including to LEL: 246, LEL to PT: 237.00, PT to UEL: 1450.00, ST to UEL: 1583.00, above UEL: 0.72
Contributions: Employee 174.01, Employer 218.55, Total 392.56
, but found 173.97M (difference of -0.04).
```

**Expected behaviour**

See above.

**Actual behaviour**

See above.

**Additional context**

Two weekly unit tests for National Insurance are currently commented out.

**Comment by paytools-reviewer** [comment]
Corrected by change to rounding - PR https://github.com/paytools-fdn/Paytools.Core/pull/18
